---
- name: Deploying the ELK
  hosts: localhost
  connection: local 
  tasks:
    - name: Copying the apk to client
      copy:
        src: ./build/app/outputs/flutter-apk
        dest: ./
    - name: Start the emulator #not needed if emulator is already up
      shell: ~/Library/Android/sdk/emulator/emulator -avd Pixel_7_Pro_API_34 &
    - name: Sleep for avd to Start
      shell: sleep 20s #no need if avd starts instantly
    - name: Starting the application
      shell: adb install ./app-release.apk
