name: Flutter Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'  # Specify the Flutter version you want to use

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/

      - name: Set up Firebase
        run: |
          echo "Downloading and installing Firebase CLI..."
          curl -sL https://firebase.tools | bash
          cd $GITHUB_WORKSPACE/build/app/outputs/flutter-apk/
          firebase init

      - name: Authenticate with Firebase
        run: |
          firebase use --add $FIREBASE_PROJECT_ID
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase
        run: |
          cd $GITHUB_WORKSPACE/build/app/outputs/flutter-apk/
          firebase deploy --only android
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
