name: Flutter Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --release

    - name: Debug
      run: |
        pwd
        ls -al
      
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Debug
      run: |
        pwd
        ls -al
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting  # Adjust this line based on your deployment needs
      env:
        FIREBASE_TOKEN: 1//0gHIDoOW3gDmpCgYIARAAGBASNgF-L9Ir2y8O2PML33O57ppgTj5Ty1wwgL7B3elYD22MXFx8P0uk9_qLzNaaGhulq7dRrpoMrQ
